export const CARREGAR_CITACOES_INICIO= 'CARREGAR_CITACOES_INICIO';
export const CARREGAR_CITACOES_SUCESSO= 'CARREGAR_CITACOES_SUCESSO';
export const CARREGAR_CITACOES_ERRO= 'CARREGAR_CITACOES_ERRO';
export const SOLICITAR_CITACAO= 'SOLICITAR_CITACAO';
